project_id = "qhoycusyoptmgvensgdu"

[functions.transcribe-audio]
verify_jwt = true

[functions.value-chain-chat]
verify_jwt = true

[functions.generate-value-chain-report]
verify_jwt = true

[functions.consultative-chat]
verify_jwt = true

[functions.generate-mvv]
verify_jwt = true

[functions.send-welcome-messages]
verify_jwt = false

[functions.culture-chat]
verify_jwt = true

[functions.generate-culture-report]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-report-notification]
verify_jwt = false

[functions.generate-anamnesis-report]
verify_jwt = true
